Add A Callback Function When Closing Connections
fcjr/martian pull request #2
Opened 2020-09-01 16:30 UTC by afranco07

This PR adds a callback when a connection is closed in martian

2020-09-23 17:58 UTC, fcjr requested changes

2020-09-23 17:58 UTC, fcjr commented on proxy.go
> +	}
this function should not be exposed to the public API, we should just do this if check where the internal function is called

2020-09-23 17:58 UTC, fcjr commented on proxy.go
> +	onClosedConnectionError func(gocontext.Context, string, error)
we should rename this to something like `onTLSConnectionClosedError`as it called for http connections

2020-09-23 20:38 UTC, afranco07 commented
@fcjr just made the changes

2020-10-06 22:59 UTC, fcjr approved these changes

2020-10-06 22:59 UTC, merged